# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('device_ip', models.GenericIPAddressField(default=None)),
            ],
        ),
    ]
