# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueServer', '0002_auto_20170908_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_info',
            old_name='device_id',
            new_name='deviceID',
        ),
        migrations.RenameField(
            model_name='device_info',
            old_name='reader_ip',
            new_name='readerIP',
        ),
        migrations.AddField(
            model_name='device_info',
            name='readerPort',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
