# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 15:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAndClientIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_ip', models.GenericIPAddressField(default=None)),
                ('reader_port', models.IntegerField(default=None)),
                ('client_ip', models.GenericIPAddressField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Device IPs and ReaderIPs',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Username', message='Username must be alphanumberic containing +-*.', regex='^[a-zA-Z0-9.@+-]*$')])),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
