# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readwrite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceandclientip',
            name='reader_port',
            field=models.IntegerField(default=None),
        ),
    ]
